version: "3.9"

services:

  # ====================
  # 🧠 Ядро AI-агента
  # ====================
  ai-engine:
    build: ./ai-engine
    container_name: ai-engine
    depends_on:
      - svc-stt
      - svc-vision
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HA_BASE_URL=http://192.168.31.81:8123
      - HA_TOKEN=${HA_TOKEN}
      - PORT=6000
    ports:
      - 6000:6000
    restart: unless-stopped
    volumes:
      - ./config/langchain_config.yaml:/app/langchain_config.yaml
      - ./config/devices.yaml:/app/devices.yaml

  # ====================
  # 🔌 Шлюзы (Gateways)
  # ====================

  gw-chat:
    build: ./gateways/chat
    container_name: gw-chat
    depends_on:
      - ai-engine
    environment:
      - CHAT_API_TOKEN=${CHAT_API_TOKEN}
      - AGENT_URL=http://ai-engine:5000/agent/process
      - PORT=5120
    ports:
      - 5120:5120
    restart: unless-stopped
    volumes:
      - ./gateways/chat/uploads:/app/uploads

  gw-audio_in:
    build: ./gateways/audio-in
    container_name: gw-audio_in
    depends_on:
      - svc-stt
    environment:
      - STT_URL=http://svc-stt:5230/stt
      - PORT=5130
    ports:
      - 5130:5130
    restart: unless-stopped
    volumes:
      - ./gateways/audio-in/recordings:/app/recordings

  gw-audio_out:
    build: ./gateways/audio-out
    container_name: gw-audio_out
    environment:
      - PORT=5140
      - TTS_URL=http://svc-tts:5240/speak
      - TTS_WAV_PATH=/shared-wav
    ports:
      - 5140:5140
    restart: unless-stopped
    volumes:
      - ./data/tts-wav:/shared-wav

  gw-screen_vision:
    build: ./gateways/screen-vision
    container_name: gw-screen_vision
    environment:
      - PORT=5160
    ports:
      - 5160:5160
    restart: unless-stopped

  gw-actuators:
    build: ./gateways/actuators
    container_name: gw-actuators
    environment:
      - PORT=5170
    ports:
      - 5170:5170
    restart: unless-stopped

  gw-face:
    build: ./gateways/face
    container_name: gw-face
    environment:
      - PORT=5180
    ports:
      - 5180:5180
    restart: unless-stopped
    volumes:
      - ./models/wav2lip/:/app/wav2lip/checkpoints

  # ====================
  # 🧠 Сервисы (Services)
  # ====================

  svc-db:
    build: ./core-services/db
    container_name: svc-db
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=5210
    ports:
      - 5210:5210
    restart: unless-stopped

  svc-stt:
    build: ./core-services/stt
    container_name: svc-stt
    environment:
      - PORT=5230
    ports:
      - 5230:5230
    restart: unless-stopped

  svc-tts:
    build: ./core-services/tts
    container_name: svc-tts
    environment:
      - PORT=5240
      - WAV_OUTPUT_DIR=/shared-wav
      - MODELS_DIR=/models
      - LD_LIBRARY_PATH=/app/piper
    ports:
      - 5240:5240
    restart: unless-stopped
    volumes:
      - ./models/tts:/models
      - ./data/tts-wav:/shared-wav
    security_opt:
      - no-new-privileges:true

  svc-vision:
    build: ./core-services/vision
    container_name: svc-vision
    environment:
      - PORT=5250
    ports:
      - 5250:5250
    restart: unless-stopped
    volumes:
      - ./models/vision:/models

  svc-screen_vision:
    build: ./core-services/screen-vision
    container_name: svc-screen_vision
    environment:
      - PORT=5260
    ports:
      - 5260:5260
    restart: unless-stopped

  # ====================
  # ⚙️ Драйверы (Drivers)
  # ====================

  drv-mic_usb:
    build: ./drivers/mic-usb
    container_name: drv-mic_usb
    depends_on:
      - gw-audio_in
    environment:
      - AUDIO_FILE=/app/audio/mock_audio.wav
      - STREAM_INTERVAL=5
      - TARGET_URL=http://gw-audio_in:5130/ingest
      - AUDIO_GATEWAY_URL=http://gw-audio_in:5130/receive-audio
      - PORT=5330
    ports: []
    restart: unless-stopped
    volumes:
      - ./mock/audio:/app/audio

  # ====================
  # 📦 Базы данных и брокеры
  # ====================

  mongo:
    container_name: mongo
    image: mongo:7
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
