services:

  # ====================
  # 🧠 Ядро AI-агента
  # ====================
  ai-engine:
    build: ./ai-engine
    container_name: ai-engine
    depends_on:
      - svc-stt
      - svc-vision
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HA_BASE_URL=http://192.168.31.81:8123
      - HA_TOKEN=${HA_TOKEN}
      - PORT=6000
    ports:
      - 6000:6000
    restart: unless-stopped
    volumes:
      - ./config/langchain_config.yaml:/app/langchain_config.yaml
      - ./config/devices.yaml:/app/devices.yaml

  # ====================
  # 🔌 Шлюзы (Gateways)
  # ====================

  gw-chat:
    build: ./gateways/chat
    container_name: gw-chat
    depends_on:
      - ai-engine
    environment:
      - CHAT_API_TOKEN=${CHAT_API_TOKEN}
      - AGENT_URL=http://ai-engine:5000/agent/process
      - PORT=5121
    ports:
      - 5121:5121
    restart: unless-stopped
    volumes:
      - ./gateways/chat/uploads:/app/uploads

  gw-frai:
    build: ./gateways/frai
    container_name: gw-frai
    environment:
      - PORT=5181
    ports:
      - 5181:5181
    restart: unless-stopped
    volumes:
      - ./models/wav2lip/:/app/wav2lip/checkpoints

  # ====================
  # 🧠 Сервисы (Services)
  # ====================
  svc-frai-audio-in:
    build: ./services/frai-audio-in
    container_name: svc-frai-audio-in
    depends_on:
      - svc-stt
    environment:
      - STT_URL=http://svc-stt:5233/stt
      - PORT=5231
    ports:
      - 5231:5231
    restart: unless-stopped
    volumes:
      - ./gateways/audio-in/recordings:/app/recordings

  svc-frai-audio-out:
    build: ./services/frai-audio-out
    container_name: svc-frai-audio-out
    environment:
      - PORT=5241
      - TTS_URL=http://svc-tts:5243/speak
      - TTS_WAV_PATH=/shared-wav
    ports:
      - 5241:5241
    restart: unless-stopped
    volumes:
      - ./data/tts-wav:/shared-wav

  svc-dev-audio-in:
    build: ./services/dev-audio-in
    container_name: svc-dev-audio-in
    depends_on:
      - svc-stt
    environment:
      - STT_URL=http://svc-stt:5233/stt
      - PORT=5232
    ports:
      - 5232:5232
    restart: unless-stopped
    volumes:
      - ./gateways/audio-in/recordings:/app/recordings

  svc-dev-audio-out:
    build: ./services/dev-audio-out
    container_name: svc-dev-audio-out
    environment:
      - PORT=5242
      - TTS_URL=http://svc-tts:5243/speak
      - TTS_WAV_PATH=/shared-wav
    ports:
      - 5242:5242
    restart: unless-stopped
    volumes:
      - ./data/tts-wav:/shared-wav

  svc-db:
    build: ./services/db
    container_name: svc-db
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017
      - PORT=5211
    ports:
      - 5211:5211
    restart: unless-stopped

  svc-stt:
    build: ./services/stt
    container_name: svc-stt
    environment:
      - PORT=5233
    ports:
      - 5233:5233
    restart: unless-stopped

  svc-tts:
    build: ./services/tts
    container_name: svc-tts
    environment:
      - PORT=5243
      - WAV_OUTPUT_DIR=/shared-wav
      - MODELS_DIR=/models
      - LD_LIBRARY_PATH=/app/piper
    ports:
      - 5243:5243
    restart: unless-stopped
    volumes:
      - ./models/piper:/models
      - ./data/tts-wav:/shared-wav
    security_opt:
      - no-new-privileges:true

  svc-vision:
    build: ./services/vision
    container_name: svc-vision
    environment:
      - PORT=5251
    ports:
      - 5251:5251
    restart: unless-stopped
    volumes:
      - ./models/vision:/models

  svc-screen_vision:
    build: ./services/screen-vision
    container_name: svc-screen_vision
    environment:
      - PORT=5261
    ports:
      - 5261:5261
    restart: unless-stopped

  svc-actuators:
    build: ./services/actuators
    container_name: svc-actuators
    environment:
      - PORT=5271
    ports:
      - 5271:5271
    restart: unless-stopped

  # ====================
  # ⚙️ Драйверы (Drivers)
  # ====================

  drv-mic-usb:
    build: ./drivers/mic-usb
    container_name: drv-mic-usb
    depends_on:
      - svc-dev-audio-in
    environment:
      - AUDIO_FILE=/app/audio/mock_audio.wav
      - STREAM_INTERVAL=5
      - TARGET_URL=http://svc-dev-audio-in:5232/ingest
      - AUDIO_GATEWAY_URL=http://svc-dev-audio-in:5232/receive-audio
      - PORT=5330
    ports: []
    restart: unless-stopped
    volumes:
      - ./mock/audio:/app/audio

  # ====================
  # 📆 Базы данных и брокеры
  # ====================

  mongo:
    container_name: mongo
    image: mongo:7
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
