services:
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2
    volumes:
      - ./config/mqtt:/mosquitto/config
      - ./data/mqtt:/mosquitto/data
      - ./log/mqtt:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  audio_stream_gateway:
    container_name: audio-stream-gateway
    build: ./services/audio-stream-gateway
    ports:
      - 5050:5050
    volumes:
      - ./services/audio-stream-gateway/recordings:/app/recordings
    environment:
      - STT_URL=http://stt-service:5060/stt
    depends_on:
      - stt_service
    restart: unless-stopped

  usb_mic_service:
    container_name: usb-mic-service
    build: ./services/usb-mic-service
    volumes:
      - ./mock/audio:/app/audio        # здесь будет храниться мок-аудио
    environment:
      - AUDIO_FILE=/app/audio/mock_audio.wav  # путь до мок-файла, можно поменять
      - STREAM_INTERVAL=5  # интервал между отправками (в секундах)
      - TARGET_URL=http://audio-stream-gateway:5050/ingest
    depends_on:
      - audio_stream_gateway
    restart: unless-stopped



  stt_service:
    container_name: stt-service
    build: ./services/stt-service
    ports:
      - "5060:5060"
    restart: unless-stopped


  vision_agent:
    container_name: vision-agent
    build: ./services/vision-agent
    volumes:
      - ./models/vision:/models
    ports:
      - 6060:6060
    restart: unless-stopped

  langchain_agent:
    container_name: langchain-agent
    build: ./ai-agent-core
    volumes:
      - ./config/langchain_config.yaml:/app/langchain_config.yaml
      - ./config/devices.yaml:/app/devices.yaml
    depends_on:
      - stt_service
      - vision_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HA_BASE_URL=http://192.168.31.81:8123
      - HA_TOKEN=${HA_TOKEN}
    restart: unless-stopped

  chat_gateway:
    container_name: chat-gateway
    build: ./services/chat-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./services/chat-gateway/uploads:/app/uploads
    environment:
      - CHAT_API_TOKEN=${CHAT_API_TOKEN}
      - AGENT_URL=http://langchain-agent:8000/agent/process
    depends_on:
      - langchain_agent
    restart: unless-stopped

  db_service:
    container_name: db-service
    build: ./services/db-service
    ports:
      - "8090:8090" 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    restart: unless-stopped

  tts_service:
    container_name: tts-service
    build: ./services/tts-service
    volumes:
      - ./models/tts:/models
    restart: unless-stopped

  speaker_service:
    container_name: speaker-service
    build: ./services/speaker-service
    ports:
      - 7070:7070
    restart: unless-stopped

  face_display:
    container_name: face-display
    build: ./services/face-display
    restart: unless-stopped

  actuator_control:
    container_name: actuator-control
    build: ./services/actuator-control
    restart: unless-stopped
